name: Daily Commit

on:
  schedule:
    - cron: '25 3 * * *'  # Runs daily at 03:25 UTC (adjust as needed)
  workflow_dispatch:      # Optional: allows manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Status File by 24ds1000138@ds.study.iitm.ac.in
        run: |
          echo "Last updated: $(date -u)" > status.txt
          git config --global user.name "devsync-bot"
          git config --global user.email "24ds1000138@ds.study.iitm.ac.in"
          git add status.txt
          git commit -m "Daily update by GitHub Actions"
          git push
